---
when:
  - event: push
    branch: main
  - event: tag
    tag: "v*"
  - event: manual

steps:
  build-snapshot:
    image: maven:3.9-eclipse-temurin-21
    when:
      - event: push
        branch: main
    commands:
      - mvn clean package -DskipTests -q
      - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - echo "Built version $VERSION"
      - echo "$VERSION" > .version

  upload-snapshot:
    image: minio/mc:latest
    when:
      - event: push
        branch: main
    environment:
      S3_ACCESS_KEY:
        from_secret: s3_access_key
      S3_SECRET_KEY:
        from_secret: s3_secret_key
    commands:
      - mc alias set minio https://s3.psalkowski.pl "$S3_ACCESS_KEY" "$S3_SECRET_KEY"
      - export VERSION=$(cat .version) && mc cp target/PeacefulPlayers-$VERSION.jar minio/minecraft-plugins/peaceful-players/PeacefulPlayers-$VERSION.jar && echo "Uploaded PeacefulPlayers-$VERSION.jar"

  build-release:
    image: maven:3.9-eclipse-temurin-21
    when:
      - event: tag
    commands:
      - VERSION=${CI_COMMIT_TAG#v}
      - echo "Building release version $VERSION"
      - mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false -q
      - mvn clean package -DskipTests -q

  upload-release:
    image: minio/mc:latest
    when:
      - event: tag
    environment:
      S3_ACCESS_KEY:
        from_secret: s3_access_key
      S3_SECRET_KEY:
        from_secret: s3_secret_key
    commands:
      - export VERSION=${CI_COMMIT_TAG#v} && mc alias set minio https://s3.psalkowski.pl "$S3_ACCESS_KEY" "$S3_SECRET_KEY" && mc cp target/PeacefulPlayers-${VERSION}.jar minio/minecraft-plugins/peaceful-players/PeacefulPlayers.jar && mc cp target/PeacefulPlayers-${VERSION}.jar minio/minecraft-plugins/peaceful-players/PeacefulPlayers-${VERSION}.jar && echo "Uploaded PeacefulPlayers-${VERSION}.jar"

  publish-modrinth:
    image: alpine:latest
    when:
      - event: tag
    environment:
      MODRINTH_TOKEN:
        from_secret: modrinth_token
    commands:
      - apk add --no-cache curl yq
      - |
        export VERSION=${CI_COMMIT_TAG#v}
        export GAME_VERSIONS=$(yq -o=json '.game_versions' modrinth.yml)
        export LOADERS=$(yq -o=json '.loaders' modrinth.yml)
        curl -X POST "https://api.modrinth.com/v2/version" \
          -H "Authorization: $MODRINTH_TOKEN" \
          -F "data={
            \"name\": \"v${VERSION}\",
            \"version_number\": \"${VERSION}\",
            \"project_id\": \"peaceful-players\",
            \"file_parts\": [\"PeacefulPlayers-${VERSION}.jar\"],
            \"dependencies\": [],
            \"game_versions\": ${GAME_VERSIONS},
            \"loaders\": ${LOADERS},
            \"version_type\": \"release\",
            \"featured\": true
          }" \
          -F "PeacefulPlayers-${VERSION}.jar=@target/PeacefulPlayers-${VERSION}.jar"
        echo "Published to Modrinth"

  bump-version:
    image: maven:3.9-eclipse-temurin-21
    when:
      - event: tag
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apt-get update -qq && apt-get install -y -qq git
      - VERSION=${CI_COMMIT_TAG#v}
      - IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
      - NEXT_MINOR=$((MINOR + 1))
      - NEXT_VERSION="${MAJOR}.${NEXT_MINOR}.0-SNAPSHOT"
      - echo "Bumping version to $NEXT_VERSION"
      - git config --global user.email "ci@homecraftmc.com"
      - git config --global user.name "HomeCraft CI"
      - git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/HomeCraftMC/peaceful-players.git
      - git fetch origin main
      - git checkout main
      - mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false -q
      - git add pom.xml
      - git commit -m "Bump version to $NEXT_VERSION [skip ci]"
      - git push origin main
